name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOGM1NzQ5YTctNzUyMi00ZGIxLWEzYzYtY2ZiZDY2NjAzYzFkIiwidGVuYW50X2lkIjoiYTkxZWM3NDM5MmRmZGIxMTg3MTQ4Yjg1ZDg3Mzg2YjllYzQwYjgyMGJlNDFmNmFkMzcxMTMyYTQwZGY1NzgyYSIsImludGVybmFsX3NlY3JldCI6ImY0MzVjZDdhLThhMTAtNDljNy1iMzZlLWI2M2ZjNTkwM2QwYyJ9.q6gzDEPvysjQOKlet4fSAfvYj1hnOBptDhIcUbuAUAA"

jwt_secret = "knacamgalznfepbhcuhgagaupt"